sudo: required

services:
  - docker

before_install:
  - docker build -t alphanganga/docker-react -f Dockerfile.dev .

script:
  - docker run -e "CI=true" alphanganga/docker-react sh -c "npm run test -- --coverage"
