sudo: required

services:
  - docker

before_install:
  - docker build -t alphanganga/docker-react -f Dockerfile.dev .

script:
  - docker run -e "CI=true" alphanganga/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-792193902576"
  bucket_path: "docker-react"
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
